package com.multigraph;

import org.graphwalker.core.machine.ExecutionContext;

import org.graphstream.graph.implementations.MultiGraph;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */
public class SomeSmallTest extends ExecutionContext implements MultiGraphTests {

  MultiGraph multiGraph = new MultiGraph("mg");
  int maxNodes = 5;
  int maxEdges = 5;

  @Test
  @Override
  public void v_NonEmptyGraph() {
    Assertions.assertTrue(this.multiGraph.getNodeCount() > 0);
  }

  @Override
  public void e_RemoveEdge() {
    this.multiGraph.removeEdge(this.multiGraph.getEdgeCount());
  }

  @Override
  public void e_AddNode() {
    this.multiGraph.addNode(String.valueOf(this.multiGraph.getNodeCount()+1));
  }

  @Test
  @Override
  public void v_EmptyGraph() {
    Assertions.assertTrue(this.multiGraph.getNodeCount() == 0 && this.multiGraph.getEdgeCount() == 0);
  }

  @Override
  public void e_Clear() {
    this.multiGraph.clear();
  }

  @Test
  @Override
  public void v_MaxNodes() {
    Assertions.assertEquals(this.maxNodes, this.multiGraph.getNodeCount());
  }

  @Test
  @Override
  public void v_MaxEdges() {
    Assertions.assertEquals(this.maxEdges, this.multiGraph.getEdgeCount());
  }

  @Override
  public void e_RemoveNode() {
    this.multiGraph.removeNode(this.multiGraph.getNodeCount()-1);
  }

  @Test
  @Override
  public void v_MaxNodesAndEdges() {
    Assertions.assertTrue(this.multiGraph.getNodeCount() == this.maxNodes && this.multiGraph.getEdgeCount() == this.maxEdges);
  }

  @Override
  public void e_AddEdge() {
    int n = this.multiGraph.getNodeCount();
    int e = this.multiGraph.getEdgeCount();
    this.multiGraph.addEdge(String.valueOf(e+1), n-2, n-1);
  }

  @Test
  public void quick_random_test() {
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodesAndEdges();
    this.e_RemoveNode();
    this.v_MaxEdges();
    this.e_AddNode();
    this.v_MaxNodesAndEdges();
    this.e_RemoveEdge();
    this.v_MaxNodes();
    this.e_Clear();
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodesAndEdges();
    this.e_Clear();
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_MaxNodes();
    this.e_RemoveEdge();
    this.v_MaxNodes();
    this.e_RemoveNode();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_MaxEdges();
    this.e_RemoveNode();
    this.v_MaxEdges();
    this.e_AddNode();
    this.v_MaxEdges();
    this.e_RemoveEdge();
    this.v_NonEmptyGraph();
    this.e_RemoveEdge();
    this.v_NonEmptyGraph();
    this.e_Clear();
    this.v_EmptyGraph();
    this.e_Clear();
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_RemoveNode();
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_NonEmptyGraph();
    this.e_AddEdge();
    this.v_MaxEdges();
    this.e_Clear();
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodesAndEdges();
    this.e_RemoveNode();
    this.v_NonEmptyGraph();
    this.e_RemoveNode();
    this.v_NonEmptyGraph();

  }

  @Test
  public void a_star_to_MaxNodesAndEdges() {
    this.v_EmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_NonEmptyGraph();
    this.e_AddNode();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodes();
    this.e_AddEdge();
    this.v_MaxNodesAndEdges();
  }

}
